import type { Category, Product } from './types';

export const SEED_CATEGORIES: Category[] = [
  { id: 'cat-biscuits', name: 'عالم البسكويت', color: '#059669', created_at: String(Date.now() - 5000) },
  { id: 'cat-drinks', name: 'المشروبات والعصائر', color: '#0d9488', created_at: String(Date.now() - 4000) },
  { id: 'cat-grains', name: 'الحبوب والأرز', color: '#0891b2', created_at: String(Date.now() - 3000) },
  { id: 'cat-oils', name: 'الزيوت والسمن', color: '#65a30d', created_at: String(Date.now() - 2000) },
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'بسكويت بالشوكولاتة - كرتون',
    category_id: 'cat-biscuits',
    price: 48,
    image: '',
    description: 'كرتون 24 قطعة بسكويت محشو بالشوكولاتة',
    created_at: String(Date.now() - 1500),
    half_carton_enabled: true,
    half_carton_price: 26,
    half_carton_units: 12,
    full_carton_units: 24,
    stock: 0,
  },
  {
    id: 'prod-2',
    name: 'بسكويت سادة - 36 وحدة',
    category_id: 'cat-biscuits',
    price: 36,
    image: '',
    description: 'كرتون 36 وحدة بسكويت سادة كلاسيكي',
    created_at: String(Date.now() - 1400),
    half_carton_enabled: false,
    half_carton_price: null,
    half_carton_units: null,
    full_carton_units: 36,
    stock: 0,
  },
  {
    id: 'prod-3',
    name: 'عصير برتقال - 24 علبة',
    category_id: 'cat-drinks',
    price: 72,
    image: '',
    description: 'كرتون 24 علبة عصير برتقال طبيعي',
    created_at: String(Date.now() - 1300),
    half_carton_enabled: true,
    half_carton_price: 40,
    half_carton_units: 12,
    full_carton_units: 24,
    stock: 0,
  },
  {
    id: 'prod-4',
    name: 'أرز مصري - كيس 25 كجم',
    category_id: 'cat-grains',
    price: 115,
    image: '',
    description: 'كيس أرز مصري فاخر وزن 25 كجم',
    created_at: String(Date.now() - 1200),
    half_carton_enabled: false,
    half_carton_price: null,
    half_carton_units: null,
    full_carton_units: null,
    stock: 0,
  },
];
